sudo: false
dist: trusty
language: rust
cache: cargo
rust:
- stable
branches:
  only:
  - master
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_script:
  - (cargo install mdbook --vers 0.2.0 --force || true)
  - (cargo install mdbook-linkcheck || true)
script:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
