sudo: false
dist: trusty
language: rust
cache: cargo
rust:
- stable
branches:
  only:
  - master
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook mdbook-linkcheck)
  - cargo install-update -a
script:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
